export const usersData = [
    { id: 1, firstName: "sandeep", lastName: "kumar", email: "jean@gmail.com" },
    { id: 2, firstName: "deepak", lastName: "luhaniwal", email: "deepakluh@gmail.com" },
    { id: 3, firstName: "sumit", lastName: "khan", email: "sumitkhan12@gmail.com" },
    { id: 4, firstName: "amit", lastName: "singh", email: "kevin@gmail.com" },
    { id: 5, firstName: "monu", lastName: "kumar", email: "manoj@gmail.com" },
    { id: 6, firstName: "manoj", lastName: "rao", email: "anil@gmail.com" },
    { id: 7, firstName: "anil", lastName: "sir", email: "ankit@gmail.com" },
    { id: 8, firstName: "ankit", lastName: "khan", email: "sumitkhan12@gmail.com" },
    { id: 9, firstName: "pardeep", lastName: "singh", email: "pardeep8763@gmail.com" },
    { id: 10, firstName: "sumit", lastName: "rao", email: "sumit4755@gmail.com" },
    { id: 11, firstName: "anil", lastName: "sir", email: "ankit@gmail.com" },
    { id: 12, firstName: "amit", lastName: "luhaniwal", email: "deepakluh@gmail.com" },
    { id: 13, firstName: "kuldeep", lastName: "kumar", email: "deepak123@gmail.com" },
    { id: 14, firstName: "ankit", lastName: "kumar", email: "deepak123@gmail.com" },
    { id: 15, firstName: "rajesh", lastName: "kumar", email: "jean@gmail.com" },
    { id: 16, firstName: "sandeep", lastName: "rao", email: "anil@gmail.com" },
    { id: 17, firstName: "deepek", lastName: "kumar", email: "manoj@gmail.com" },
    { id: 18, firstName: "sumit", lastName: "rao", email: "monu@gmail.com" },
    { id: 19, firstName: "monu", lastName: "singh", email: "pardeep8763@gmail.com" },
    { id: 20, firstName: "amit", lastName: "singh", email: "kevin@gmail.com" },
]